# dev only
-
  environment:
    package_semantic_version: 1.0.0
  version: $(package_semantic_version).{build}
  pull_requests:
    do_not_increment_build_number: true
  branches:
    only:
    - develop
  skip_tags: true
  skip_commits:
    files:
      - .editorconfig
      - .gitattributes
      - .gitignore
      - appveyor.yml
      - LICENSE
      - README.md
      - Settings.StyleCop
      - Autofac.Extras.CommonServiceLocator.sln
      - Autofac.Extras.CommonServiceLocator.sln.DotSettings
      - '**/*.csproj'
  image: Visual Studio 2017
  configuration: Debug
  platform: Any CPU
  dotnet_csproj:
    patch: true
    file: '**\*.csproj'
    version: '$(package_semantic_version).0'
    package_version: '$(package_semantic_version).0'
  nuget:
    disable_publish_on_pr: true
  build_script:
  - ps: .\build-solution.ps1 -Configuration $env:configuration -Platform $env:platform

# release Only
-
  environment:
    package_semantic_version: 1.0.0
  version: $(package_semantic_version).{build}
  pull_requests:
    do_not_increment_build_number: true
  branches:
    only:
    - release/all
  skip_tags: true
  # skip_commits:
  #   files:
  #     - .editorconfig
  #     - .gitattributes
  #     - .gitignore
  #     - appveyor.yml
  #     - LICENSE
  #     - README.md
  #     - Settings.StyleCop
  #     - Autofac.Extras.CommonServiceLocator.sln
  #     - Autofac.Extras.CommonServiceLocator.sln.DotSettings
  #     - '**/*.csproj'
  image: Visual Studio 2017
  configuration: Release
  platform: Any CPU
  dotnet_csproj:
    patch: true
    file: '**\*.csproj'
    version: '$(package_semantic_version).0'
    package_version: '$(package_semantic_version).0'
  nuget:
    disable_publish_on_pr: true
  build_script:
  - ps: .\build-solution.ps1 -Configuration $env:configuration -Platform $env:platform
  artifacts:
  - path: .\src\Autofac.Extras.CommonServiceLocator\**\*.nupkg
    name: Autofac.Extras.CommonServiceLocator
  deploy:
  - provider: Environment
    name: NuGet for Autofac.Extras.CommonServiceLocator
